---
- hosts: kubernete_master
  become: yes
  gather_facts: false
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- hosts: kubernete_slave
  environment:
  become: yes
  tasks:

    - name: Generate no_proxy
      shell: |
        printf -v lan '%s,' {{ lan_range }}
        printf -v pool '%s,' 10.244.0.{1..253}
        printf -v service '%s,' 10.96.0.{1..253}
        echo "${lan%,},${service%,},${pool%,},127.0.0.1"
      register: no_proxy_value     

    - name: join cluster
      environment:
        no_proxy: "{{ no_proxy_value }}"
      shell: "{{ hostvars['master-kubernete'].join_command }}"
      register: result
