---
- hosts: kubernete_master
  environment:
    http_proxy: "{{http_proxy}}"
    https_proxy: "{{https_proxy}}"
  become: yes
  gather_facts: false
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- hosts: kubernete_slave
  environment:
    http_proxy: "{{http_proxy}}"
    https_proxy: "{{https_proxy}}"
  become: yes
  tasks:

    - name: join cluster
      shell: "{{ hostvars['master-kubernete'].join_command }}"
      register: result

    - name: debug join cluster command
      debug:
        var: result
