---
- hosts: all
  become: yes
  tasks:
    
    - name: Create the 'esbmc' user
      user: name=esbmc append=yes state=present createhome=yes shell=/bin/bash

    - name: Allow 'esbmc' to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        line: "esbmc ALL=(ALL) NOPASSWD: ALL"
        validate: "visudo -cf %s"

    - name: Set up authorized keys for the esbmc user
      authorized_key: user=esbmc key="{{item}}"
      with_file:
        - ~/.ssh/id_rsa.pub

    - name: Disable SWAP since kubernetes can't work with swap enabled
      shell: |
        swapoff -a

    - name: Disable SWAP in fstab since kubernetes can't work with swap enabled
      replace:
        path: /etc/fstab
        regexp: '^(.+?\sswap\s+sw\s+.*)$'
        replace: '# \1'
  
    - name: Start service Firewalld
      service:
        name: firewalld
        state: started

    - name: Allow Network Ports in Firewalld
      firewalld:
        port: "{{ item }}"
        state: enabled
        permanent: yes
        immediate: yes
      with_items: "{{ ports }}"

