---
- hosts: all
  become: yes
  tasks:
    - name: Change hostname since kubernetes doesn't work with same hostnames
      shell: "hostnamectl set-hostname {{inventory_hostname}}"

    - name: Create the 'esbmc' user
      user: name=esbmc append=yes state=present createhome=yes shell=/bin/bash

    - name: Allow 'esbmc' to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        line: "esbmc ALL=(ALL) NOPASSWD: ALL"
        validate: "visudo -cf %s"

    - name: Set up authorized keys for the esbmc user
      authorized_key: user=esbmc key="{{item}}"
      with_file:
        - ~/.ssh/id_rsa.pub

    - name: Disable SWAP since kubernetes can't work with swap enabled
      shell: |
        swapoff -a

    - name: Disable SWAP in fstab since kubernetes can't work with swap enabled
      replace:
        path: /etc/fstab
        regexp: '^(.+?\sswap\s+sw\s+.*)$'
        replace: '# \1'
