apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins
  name: jenkins
  namespace: deployment-jenkins
spec:
  ports:
  - name: http-port
    nodePort: 30500
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: jnlp-port
    nodePort: 30501
    port: 50000
    protocol: TCP
    targetPort: 50000
  selector:
    app: jenkins
  type: NodePort