---

- hosts: kubernete_master
  environment:
    http_proxy: "{{http_proxy}}"
    https_proxy: "{{https_proxy}}"
  become: yes  
  tasks:

  - name: Copy jenkins-deployment.yml to esbmc user
    copy:
      src: "{{ playbook_dir }}/jenkins-deployment.yml"
      dest: /home/esbmc/jenkins-deployment.yml
      remote_src: yes
      owner: esbmc

  - name: Copy jenkins-service.yml to esbmc user
    copy:
      src: "{{ playbook_dir }}/jenkins-service.yml"
      dest: /home/esbmc/jenkins-service.yml
      remote_src: yes
      owner: esbmc

  - name: Generate no_proxy
    shell: |
      printf -v lan '%s,' {{ lan_range }}
      printf -v pool '%s,' 10.244.0.{1..253}
      printf -v service '%s,' 10.96.0.{1..253}
      echo "${lan%,},${service%,},${pool%,},127.0.0.1"
    register: no_proxy_value       

  - name: Start jenkins    
    become_user: esbmc
    environment:
        no_proxy: "{{ no_proxy_value }}"
    shell: kubectl create -f $HOME/jenkins-deployment.yml

  - name: Start jenkins load balancer    
    become_user: esbmc
    environment:
        no_proxy: "{{ no_proxy_value }}"
    shell: kubectl create -f $HOME/jenkins-service.yml