---
- hosts: kubernete_master
  become: true
  environment:
    http_proxy: "{{http_proxy}}"
    https_proxy: "{{https_proxy}}"
  tasks:
    - name: Ensure java8 is Installed
      yum:
        name: java-1.8.0-openjdk-devel
        state: present
        update_cache: yes
    - name: Ensure Jenkins Repository is Installed
      yum_repository:
        name: jenkins
        state: present
        description: Official Jenkins Yum Repo
        baseurl: http://pkg.jenkins.io/redhat
        gpgkey: https://jenkins-ci.org/redhat/jenkins-ci.org.key
        gpgcheck: no
        enabled: yes
    - name: Ensure Jenkins is Installed
      yum :
        name: jenkins
        update_cache: yes
        state: present
    - name: Enable and Start the Jenkins Service
      service:
        name: jenkins
        enabled: yes
        state: started
    - name: Ensure git is installed
      yum:
        name: git
        update_cache: yes
        state: present